title: Fake it till you make Git

description: >
  An (opinionated) approach to Git and GitHub

author:
  name: Nicola Erario
  email: 'nicola.erario@gmail.com'

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: 'https://github.com/nicolaerario' }
    - { platform: linkedin, user_url: 'https://www.linkedin.com/in/nicolaerario/' }
  date_format: '%e %b %Y'

header_pages:
  - index.md
  - docs/it/index_it.md
  - blog.md

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

show_excerpts: true

defaults:
  - scope:
      path: ''
    values:
      image: assets/images/Fake_it_till_you_make_git.png
